name: workflow with artifacts 
on: push 
env:
 ARTIFACT_NAME: my banana artifact 
jobs: 
 trial_job:
   runs-on: ubuntu-latest
   steps:
    - name: checkout the code
      uses: actions/checkout@v2
    - name: upload artifact 
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.ARTIFACT_NAME}}
        Path: .
     
